// Mirror of the server-side list in supabase/migrations/0006_username_finalize.sql.
// Kept in sync manually; the server check is authoritative.
export const RESERVED_USERNAMES: readonly string[] = [
  'admin',
  'administrator',
  'root',
  'support',
  'help',
  'staff',
  'team',
  'arena',
  'challengearena',
  'api',
  'www',
  'app',
  'mobile',
  'signup',
  'signin',
  'login',
  'logout',
  'register',
  'onboarding',
  'me',
  'you',
  'user',
  'users',
  'profile',
  'settings',
  'test',
] as const;
